### ISSUE TITLE
4L

### ISSUE THREAD

**Issue by lsoz** [majhcc/TikTok-Checker#1]
Is there a way to check for 4 letter?

**Comment by m7medVision** [comment]
Yes,

change the number 6 to 4  in this line : [here](https://github.com/majhcc/TikTok-Checker/blob/36c0fc61cfd2da29cdd794fa80c528bfeae95e70/TikTok%20Checker.py#L32) 

from
` User= ''.join(random.choice(letters) for i in range(6))`
to 
` User= ''.join(random.choice(letters) for i in range(4))`
